### ISSUE TITLE
Technical Hotline: Missing ring-tone/hold music while on hold 

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-hotline#1]
I called the technical hotline mentioned in the app +498007540001.

After selecting "German" and "Technical Help" I was told to "hold", then for one minute, while on hold, **no sound was played at all**.

Clear hotline bug, not related to the app itself but needs to be made known to Telekom/Hotline-Team. This is the best place where such things can be transparently reported.

Suggestion: Maintainers to email Telekom-Hotline team and send link to this issue.

**Comment by SebastianWolf-SAP** [comment]
Dear @corneliusroemer ,

thank you very much for your proposal.

Issues or questions concerning the Corona-Warn-App hotlines have no direct connection to the work here in the open source community. However, to give the community the chance to report their ideas for the hotline, we created the cwa-hotline repository.

This issue contains an idea for at least one of the hotlines. Consequently, we will move this issue to this repository and allow the community and you to further refine or to discuss it.

All issues in the cwa-hotline repository will be discussed with the entities which are responsible for the hotline. Once a decision about the implementation has been made, we will let you know about the details.

Best regards,
SW
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Just checked this issue, although there are some ring tones there is still no music. But, all ca. 5 seconds a voice said "Einen Moment bitte". 
Maybe you would like to check this again @corneliusroemer?

**Comment by Ein-Tim** [comment]
I suggest to close this issue @dsarkar.

**Comment by dsarkar** [comment]
@Ein-Tim  Sure. Closing this issue. @corneliusroemer @Ein-Tim thanks for contributing here!

**Comment by MikeMcC399** [comment]
@brianebeling 

According to the previous comment, this issue was supposed to be closed. It is however still showing as an open issue.

**Comment by brianebeling** [comment]
Closed as its not relevant anymore / has been fixed in the meantime
