### ISSUE TITLE
Technical hotline suggest to call verification hotline on positive quick test

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-hotline#10]
## Which hotline
App/Technical hotline

## Describe the issue
Somebody on Twitter [told me](https://twitter.com/sbamueller/status/1377938804116484097?s=21) that the technical hotline said him that if a quick test returns positive, the verification hotline should be called to get a TAN and warn others. 

According to https://www.coronawarn.app/en/faq/#rapid_test, it is currently not supported to enter quick tests into the app. 
The blog post "[Die Bundesregierung integriert Schnelltests in die Corona-Warn-App](https://www.coronawarn.app/de/blog/2021-03-31-corona-warn-app-test-integration/)" says:
"Die App integriert **künftig** Schnelltests. "

Both sources make it very clear that you shouldn't add quick tests into the app currently.

## Suggested change
Please 
1. Clarify wether it is suggested to add positive quick test results into the app via calling the verification hotline
2. If it's not suggested, please make sure that hotline staff doesn't advice people to do this.

**Comment by Ein-Tim** [comment]
This is **not** an enhancement, please relabel.

Thanks!

**Comment by dsarkar** [comment]
@Ein-Tim I will bring it up internally. Thanks.

**Comment by Ein-Tim** [comment]
Although it should now, with the release of version 2.1, be clearer what to do, I'll close this issue once somebody from the team ensures that hotline staff was instructed to not issue any TeleTANs for quick tests.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> Although it should now, with the release of version 2.1, be clearer what to do, I'll close this issue once somebody from the team ensures that hotline staff was instructed to not issue any TeleTANs for quick tests.

The FAQ [Can I share my positive rapid antigen test result via the TAN hotline?](https://www.coronawarn.app/en/faq/#rat_tan_hotline) says:

"It is not possible to share a positive rapid test result via the TAN hotline. Only rapid test results communicated via the app have been performed according to the dual control principle and by trained personnel, and can therefore be shared."

so that also makes it very clear.

**Comment by Ein-Tim** [comment]
I guess we won't get an answer here, so closing this issue.
