### ISSUE TITLE
Technical Hotline: Unfriendly or no response after massive Testresult-Server incident

### ISSUE THREAD

**Issue by vaubaehn** [corona-warn-app/cwa-hotline#15]
Dear @daniel-eder ,

you probably read about the heavy incident here https://github.com/corona-warn-app/cwa-app-android/issues/968 today.
Now many people are left behind with invalid test registrations. When they call the technical hotline to seek help, many people get either unfriendly responses or no response at all (see e.g. reports in Google Play Store for the CWA).
Beside the question, why server deployments/maintenance need to be done during the day time, I kindly ask you to forward the subsequent problems with the staff in the technical hotline to the stakeholders.
In all, what happened today does not shed a positive light at TSI.
Thanks a lot in advance for your reply.

Cc: @mlenkeit @thomasaugsten @dsarkar
FYI: @Ein-Tim

---
Internal Tracking ID: [EXPOSUREAPP-10939](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10939)

**Comment by dsarkar** [comment]
Good morning @vaubaehn, thanks: Internal Tracking ID: [EXPOSUREAPP-10939](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10939)

**Comment by daniel-eder** [comment]
@vaubaehn Thank you for reporting this!
I brought this issue to the attention of the workstream lead for the hotline. I'm sorry for the bad experience users had and hope these issues will be addressed swiftly!

**Comment by daniel-eder** [comment]
I just got confirmation that the hotline stakeholders are aware of the (significantly) increased call volume yesterday and the related service issues. These issues are being addressed now.

I am closing this issue - if any new issues arise please feel free to open a new ticket and ping me.

**Comment by vaubaehn** [comment]
Good morning, @daniel-eder , thank you very much, once again. I am very happy that we can count on your support.
Have a good week!
