### ISSUE TITLE
Why does the TAN hotline ask how long the app has been installed and does only issue a TAN if the app has been installed for more than 14 days?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-hotline#16]
## Your Question
Multiple users on Twitter reported that the TAN hotline refused to give them a TAN because the app was not installed long enough. The staff asked for how long the app has been installed & if the app hasn't been installed for more than 14 days, the hotline does not issue a TAN. Why is this the case? IHMO, users should always be able to warn others (but if they just installed the app). 

---
Internal Tracking ID: [EXPOSUREAPP-11126](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11126)

**Comment by dsarkar** [comment]
@Ein-Tim Will try to get an answer: Internal Tracking ID: [EXPOSUREAPP-11126](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11126)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks a lot, could you link the twitter reports, please?

**Comment by Ein-Tim** [comment]
@dsarkar I will have to search, give me some time, please (-:

**Comment by Ein-Tim** [comment]
I did not found the twitter reports I opened this issue on, but another user confirmed that this question is asked and if the app is not installed "long enough", no TAN is issued: https://twitter.com/FunchalFish/status/1481332621347115009?s=20

**Comment by GisoSchroederSAP** [comment]
I double-checked with the TAN Hotline:
The agents ask how long the app was running on the device before the PCR test was performed. If the app just was installed to retrieve the test result, the user did not do contact tracing at all til now. Therefore, warning with TAN does not make sense in this case.
If the app was running before the test date, the user will get a TAN to warn others.

From my perspective, this issue can be closed. If required, we can enhance the FAQ article(s) that deal with the TAN procedure.

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP 

Okay, thanks for cross checking. Closing.
