### ISSUE TITLE
Technical Hotline: Overcomplicated language selection process at beginning of call

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-hotline#2]
I called the technical hotline mentioned in the app +498007540001.

## Problem 
It takes 35s to get past language selection German/English. This is far too long. This is the logic (but more wordy than this):
1. (in German) For German stay on the line
2. (in German) For English say or press 1
3. (in English) For German stay on the line
4. (in English) For English say or press 1

This is a link to a recording of the "Ansage":
https://voca.ro/ggbADUblyDx

## Suggestion

A much more concise and clearer logic is:
1. (In German) For German say or press 1 (allow people to say or press 1 already there for shortcut)
2. (In English) For English say or press 2
3. Wait 5 seconds
4. Continue in German unless 2 pressed or said

Hotline bug, not related to the app itself but needs to be made known to Telekom/Hotline-Team. This is the best place where such things can be transparently reported.

Suggestion: Maintainers to email Telekom-Hotline team and send link to this issue.

---
Internal Tracking ID:  [EXPOSUREAPP-5150](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5150)

**Comment by SebastianWolf-SAP** [comment]
Dear @corneliusroemer ,

thank you very much for your proposal.

Issues or questions concerning the Corona-Warn-App hotlines have no direct connection to the work here in the open source community. However, to give the community the chance to report their ideas for the hotline, we created the cwa-hotline repository.

This issue contains an idea for at least one of the hotlines. Consequently, we will move this issue to this repository and allow the community and you to further refine or to discuss it.

All issues in the cwa-hotline repository will be discussed with the entities which are responsible for the hotline. Once a decision about the implementation has been made, we will let you know about the details.

Best regards,
SW
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Seems solved @corneliusroemer:

Now the process is like this:

"Für Deutsch sagen oder wählen Sie 0"
"Für Englisch sagen oder wählen Sie 1" 
"Für Türkisch sagen oder wählen Sie 2"

The this gets repeated in English & Turkish.

**Comment by dsarkar** [comment]
@Ein-Tim Still valid issue?

**Comment by Ein-Tim** [comment]
@dsarkar 

Yes, just checked, still valid too.

**Comment by dsarkar** [comment]
@Ein-Tim Many thanks, very much appreciated! Will be tracked separately now: [EXPOSUREAPP-5150](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5150)

**Comment by dsarkar** [comment]
new ticket: [EXPOSUREBACK-973](https://jira-ibs.wbs.net.sap/browse/EXPOSUREBACK-973)

**Comment by MikeMcC399** [comment]
@corneliusroemer 

This issue is probably obsolete now, since the Technical Hotline only covers German. See https://www.coronawarn.app/en/faq/results/#international_phone_numbers.

Perhaps @Ein-Tim would like to check, since he was the last person here actively involved (see https://github.com/corona-warn-app/cwa-hotline/issues/2#issuecomment-779262364)?

**Comment by Ein-Tim** [comment]
@MikeMcC399 Will check tomorrow when the technical is in service again.

**Comment by Ein-Tim** [comment]
There is no language selection process at the technical hotline anymore.

**Comment by Ein-Tim** [comment]
This issue is obsolete and should be closed.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for the hint!
