### ISSUE TITLE
Why is there no estimated waiting time?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-hotline#21]
## Your Question
Other hotlines offer the service that while one is in the waiting line, the computer voice does not only tell that all available staff is already in talks with other customers, but also how long the estimated waiting time is.
Why is the CWA hotline not offering this service?

**Comment by dsarkar** [comment]
@Ein-Tim I have forwarded this question. Stand by, please, thanks.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I'm not sure whether this issue was about the Technical or the TAN hotline. If it was only about the TAN hotline then it could be closed.

**Comment by Ein-Tim** [comment]
@MikeMcC399 It's mainly about the TAN hotline, so I'll close this now.
