### ISSUE TITLE
TAN Hotline: Add information for which tests a TAN can be issued at the beginning of the call

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-hotline#24]
## Current Implementation
Currently, what I heard from users on Twitter, there is no information at the beginning of the call for which tests a TAN can be generated.

## Suggested Enhancement
At the following information at the beginning of the call:
"Please note that the TAN hotline can only issue TANs for PCR-Test, which were analyzed in a laboratory. It is not possible to request a TAN for rapid PCR tests (result arrives 4-8h after the sample was taken) or for rapid antigen tests (result arrives 15-30 minutes after the sample was taken).

## Expected Benefits
Multiple:
1. Users who want to request a TAN for their rapid PCR or rapid antigen test are informed instantly that they won't get a TAN for their test, so they can hang up again
2. Less people on hold, less waiting time, better experience for the users who have a normal PCR tests which a TAN can be issued for

---
Internal Tracking ID: [EXPOSUREAPP-12871](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12871)

**Comment by larswmh** [comment]
Thanks for your enhancement request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12871](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12871)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@dsarkar True, I will relay this information to the Twitter user.
