### ISSUE TITLE
Drop requirement that PCR test needs to be performed by a laboratory

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-hotline#25]
The hotline does not issue TANs for PCR tests, which were performed by e.g. local pharmacies, which also examined the result.
As these pharmacies can't connect to the CWA test system, users call the TAN hotline, wait for a long time only to be told that the TAN hotline does not issue TANs for these test.
This requirement makes 0 sense and should be dropped. Also, these pharmacies, etc. should be allowed to connect to CWAs test result system.

Here's a Tweet from a user this: https://twitter.com/autzeit/status/1539886506055188480?s=21&t=d8NN0yPCE0JsTSQe-pUtBQ

---
Internal Tracking ID: [EXPOSUREAPP-13570](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13570)

**Comment by MikeMcC399** [comment]
@Ein-Tim 

You bring up a valid point in this issue. I presume that this is about [Rapid PCR tests](https://www.coronawarn.app/en/faq/results/#glossary_rapid_pcr_test) as described in the Glossary which says "At the moment it is not possible to get a Rapid PCR Test result in the Corona-Warn-App, but the technical preparations have already been implemented in version 2.19.".

I don't think there was any restriction on pharmacies connecting to the CWA in the past, however as you know, no new requests are being accepted by TSI for integration of rapid test centres (see https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki).

There are ongoing political discussions at the moment which will significantly affect the [national test strategy](https://www.bundesgesundheitsministerium.de/coronavirus/nationale-teststrategie/faq-covid-19-tests.html) after the current [TestV](https://www.gesetze-im-internet.de/coronatestv_2021-10/) expires next week on June 30, 2022. 

I have not seen any mention in the press in the last days about Rapid PCR tests. Mostly the discussions have been about reducing the costs of Bürgertests in total (for example https://www.n-tv.de/politik/Lauterbach-will-Gratis-Buergertests-fuer-alle-beenden-article23417160.html).

It would be good to have a statement from those responsible here how they view the future handling of Rapid PCR Tests by the Corona-Warn-App and its associated infrastructure. As far as I know this has never been explained.

**Comment by Ein-Tim** [comment]
@MikeMcC399 I'm currently in contact with the user trying to clarify if this is about a rapid PCR test or a normal PCR test.

**Comment by Ein-Tim** [comment]
Another Twitter report: https://twitter.com/flom0ps/status/1545723648190849024?s=20&t=idwrrcMZKLB6dnCeKeJaUQ

In general the question arises: What about RT-PCR-tests. These are not rapid PCR tests but normal PCR tests, but it seems like the hotline is not allowed to issue TANs.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for forwarding this case. We will forward this info that without stating the lab on the results document fitted by the test centre, no TAN is issued by the hotline.

**Comment by Ein-Tim** [comment]
@dsarkar 

Thank you. It would be good to know & have a clear statement from the team for which types of tests a TAN actually is issued.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- The draft PR https://github.com/corona-warn-app/cwa-app-android/pull/5677 would resolve this restriction.

**Comment by Ein-Tim** [comment]
Implemented with version 3.0 and therefore obsolete.
