### ISSUE TITLE
Make it possible to requests TANs for multiple people during one call

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-hotline#26]
There are Twitter users which report that the staff on the TAN hotline tells them that they are not allowed to issue TANs for multiple persons during one call. This means in praxis, that if a family of f.i. 4 people caught COVID and want to get a TAN, each family member has to call the hotline, wait in the waiting line and reduces capacity for other people. 
I don't understand why there is a rule that says that during one call only TANs for one person can be issued. Amid the situation that the hotline is totally overcrowded all the team, it would only make sense to drop this rule. 

---
Internal Tracking ID: [EXPOSUREAPP-13536](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13536)

**Comment by Ein-Tim** [comment]
@dsarkar 

One link: https://twitter.com/anorakkapuze/status/1544245299404713984?s=20&t=qlhcdsNMR2gTtnuxzvB6nQ

I will search for some more, but no guarantee I'll find them.

**Comment by Ein-Tim** [comment]
One more: https://twitter.com/balticcowboy/status/1544597025488076800?s=21&t=kBqufhctwjZgpbAKo7WSYg

**Comment by MikeMcC399** [comment]
@Ein-Tim 

This issue is no longer relevant and can be closed, since the TAN hotline closed down today. See [README](https://github.com/corona-warn-app/cwa-hotline/blob/master/README.md).
