### ISSUE TITLE
Waiting loop: Reduce frequency of information that all staff is currently busy

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-hotline#27]
There are multiple users on Twitter who complain about the frequency of the information that all staff is currently busy. it seems like the information is played way too often and is not helpful but only annoying the user.

See:
- https://twitter.com/Dr1f73r/status/1512372229882925058?s=20&t=qlhcdsNMR2gTtnuxzvB6nQ
- https://twitter.com/MaybeMartinJ/status/1544252091966918656?s=20&t=qlhcdsNMR2gTtnuxzvB6nQ
- https://twitter.com/DerKoki/status/1544319238491496455?s=20&t=qlhcdsNMR2gTtnuxzvB6nQ

---
Internal Tracking ID: [EXPOSUREAPP-13538](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13538)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks, will be forwarded to corresponding entities!

**Comment by MikeMcC399** [comment]
@Ein-Tim 

This issue is no longer relevant and can be closed, since the TAN hotline closed down today. See [README](https://github.com/corona-warn-app/cwa-hotline/blob/master/README.md).
