### ISSUE TITLE
Automatize as many steps in the hotline process as possible

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-hotline#28]
To make life easier for both, staff and users calling the hotline, it would be favorable if the following steps in the hotline process would be made automatic:
1. Read out the data protection note - after reading it out ask "Do you agree to these terms & conditions?" and use the same system as in the beginning of the call ("If you agree, say 'Yes' or press 1" / "If you disagree say 'No' or press 2").
2. Establish an automatic call-back system.

---

The user flow would look like this:

1. Call the hotline
2. Decide which language you need
3. While on hold, the data protection informations are read out
4. Agree or disagree to these terms & conditions as described above
5. Wait until you are connected to staff
6. Staff makes sure you are actually positive, asks you some questions and enters your phone number into the system
7. Hang up
8. Wait until you are called back
9. The TAN is automatically read out to you

This improvement would significantly improve the process and more calls could be processed, as time is saved by automating as many steps in the process as possible. 

---
Internal Tracking ID: [EXPOSUREAPP-13572](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13572)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for the suggestions.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

This issue is no longer relevant and can be closed, since the TAN hotline closed down today. See [README](https://github.com/corona-warn-app/cwa-hotline/blob/master/README.md).
