### ISSUE TITLE
Missing CODE of CONDUCT

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-hotline#29]
This repository has no CODE of CONDUCT published.

## Suggestion

Add

```
## Code of Conduct

This project has adopted the [Contributor Covenant](https://www.contributor-covenant.org/) in version 2.0 as our code of conduct. Please see the details in our [CODE_OF_CONDUCT.md](CODE_OF_CONDUCT.md). All contributors must abide by the code of conduct.

```
to the [README](https://github.com/corona-warn-app/cwa-hotline/blob/master/README.md) file in this repository and copy https://github.com/corona-warn-app/cwa-documentation/blob/main/CODE_OF_CONDUCT.md to this repository.

**Comment by daniel-eder** [comment]
@MikeMcC399 thank you! Due to this not being an active dev repo this was overlooked, but should absolutely be added. I will PR this in a minute
