### ISSUE TITLE
[Accessibility] Technical Hotline: Hotline doesn't ask for "say 1" for those tested positively, just "press 1"

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-hotline#3]
I called the technical hotline mentioned in the app +498007540001.

## Problem 
This is the logic (but more wordy than this):
1. If you have been positively tested, **press** 1
2. If you have other questions around Corona, **say or press** 2
3. If you need help with the app, **say or press** 3

In 1 it doesn't ask for "say" making it less accessible for blind/visually impaired people than 2/3.

This is a link to a recording of the "Ansage":
https://voca.ro/ggbADUblyDx

## Suggestion

1. If you have been positively tested, **say or** press 1
2. If you have other questions around Corona, say or press 2
3. If you need help with the app, say or press 3

Hotline bug, not related to the app itself but needs to be made known to Telekom/Hotline-Team. This is the best place where such things can be transparently reported.

Suggestion: Maintainers to email Telekom-Hotline team and send link to this issue.

---
Internal Tracking ID:  [EXPOSUREAPP-5149](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5149)

**Comment by SebastianWolf-SAP** [comment]
Dear @corneliusroemer ,

thank you very much for your proposal.

Issues or questions concerning the Corona-Warn-App hotlines have no direct connection to the work here in the open source community. However, to give the community the chance to report their ideas for the hotline, we created the cwa-hotline repository.

This issue contains an idea for at least one of the hotlines. Consequently, we will move this issue to this repository and allow the community and you to further refine or to discuss it.

All issues in the cwa-hotline repository will be discussed with the entities which are responsible for the hotline. Once a decision about the implementation has been made, we will let you know about the details.

Best regards,
SW
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
This is only about German language, English is correct.

**Comment by dsarkar** [comment]
@Ein-Tim This has been lying around a long time. Would you do me a favor and cross-check? Many thanks.

**Comment by Ein-Tim** [comment]
@dsarkar 

Yes this is still the case.

**Comment by dsarkar** [comment]
@Ein-Tim Many thanks, very much appreciated! Will be tracked separately now: EXPOSUREAPP-5149

**Comment by dsarkar** [comment]
@Ein-Tim This issue was fixed. Do you want to cross-check?  
@corneliusroemer I that case, we suggest closing this issue.

Thanks to everybody for contributing here.

**Comment by Ein-Tim** [comment]
@dsarkar 

Thanks, I can confirm that it's fixed!

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for checking.

**Comment by dsarkar** [comment]
Solved. Closing this issue. Thanks to everybody for contributing.
