### ISSUE TITLE
Future of TAN hotline?

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-hotline#31]
The Android app [3.0.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/3.0.x) version in development has added "Self Report Submission" (SRS) and removed the TAN submission cards from visibility (see PR https://github.com/corona-warn-app/cwa-app-android/pull/5677).

If "Self Report Submission" (SRS) will allow warning without being in possession of a TAN, then there will be no need for a TAN hotline for users of a future CWA 3.x app.

Does this mean that the TAN hotline will be shut down or will it continue its operation for users who are still on a 1.x or 2.x version, including those on the community [CCTG](https://codeberg.org/corona-contact-tracing-germany/cwa-android/) version?

**Comment by MikeMcC399** [comment]
The question seems to be answered in 
https://github.com/corona-warn-app/cwa-app-android/blob/6fb6a5e17a889e4b0f01b73287c83c607dc0fd5b/Corona-Warn-App/src/main/res/values/release_info_strings.xml#L30

if / when CWA 3.0 is released:

"Die Möglichkeit, eine TAN über die TAN-Hotline zu erhalten, entfällt in einigen Wochen. Sie können nun ohne TAN andere Nutzer der Corona-Warn-App warnen."

**Comment by Ein-Tim** [comment]
@MikeMcC399 The remaining question is:
When will the hotline be shut off?

**Comment by MikeMcC399** [comment]
CWA 3.0 has been announced via [Twitter](https://twitter.com/BMG_Bund/status/1601146184537583617) with release date Wednesday, Jan 18, 2023. (Thanks to @Ein-Tim for the information!)

There has not been any official statement about shutting down the hotline as yet, however this seems to be the mostly likely outcome.

**Comment by MikeMcC399** [comment]
It seems that there will be no feedback here before the actual release of CWA 3.0 so I'm closing this issue.
