### ISSUE TITLE
Remove positive option from technical hotline

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-hotline#36]
## Which hotline
+49 800 7540001

## Current Implementation
The first option the technical hotline offers you to select is "Wenn Sie positiv auf das Coronavirus gestetst wurden, drücken oder sagen Sie jetzt bitte die Eins." When you select this option, you only get the information that the TAN hotline has been shut down, or, to be more specific, you hear the same thing you hear when calling the TAN hotline. 

## Suggested Enhancement 
Remove the first option.

## Expected Benefits
It is not needed anymore, and fewer options lead to a faster way through the menu for the user. 

---
Internal Tracking ID: [EXPOSUREAPP-14675](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14675)

**Comment by larswmh** [comment]
Thanks for your enhancement request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-14675](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14675)

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Hi @Ein-Tim, thanks for creating this issue. After pressing "1" the user gets the info that the verification hotline is not available anymore, however, he gets also instructions how to use the new SRS feature of the CWA version 3.0, which is a rather long message.

There are advantages to keep it this way:
- The user gets 3 options to choose from: 
  - 1. he is positive, 
  - 2. he has personal questions regarding COVID-19, 
  - 3. he needs technical assistance regarding the CWA
- if he then chooses option "1", he gets a more detailed message about the SRS feature. 
  - Particularly mentioning the SRS feature is useful information to the user, so it should be kept
  - User who call the hotline for other reasons (options "2" or "3") are most probably not interested in that detail

If Option "1" would be removed, the information about the SRS feature could be introduced before offering the two remaining options, however, this would make the message even longer.

**Comment by Ein-Tim** [comment]
@dsarkar These are excellent arguments, and I'm with you that it is be a good idea to keep it that way!
