### ISSUE TITLE
Barrierefreiheit für Schwerhörige, Ertaubte und Gehörlose

### ISSUE THREAD

**Issue by JoachimSeuling** [corona-warn-app/cwa-hotline#4]
Ich finde keine Informationen, wie Menschen, die nicht per Telefon kommunizieren können, Informationen erhalten sollen bzw. mit der App interagieren sollen. Wie sollen Nutzer z.B. eine TAN erhalten, wenn sie infiziert sind. Gibt es dafür einen Chat?

**Comment by JoachimSeuling** [comment]
vielen Dank

**Comment by Ein-Tim** [comment]
![image](https://user-images.githubusercontent.com/67682506/102089620-c597d300-3e1c-11eb-9e1c-1b3b05233004.jpeg)

I don't know if this solved the problem, but the Hotline now supports "Tess-Relay".
I am not an expert reg. this topic, just wanted to inform you about this @JoachimSeuling

**Comment by JoachimSeuling** [comment]
Danke für die Information. 
Tess ist allerdings nur für Notufe zur 112 und 110 kostenlos. Für alle anderen Anrufe ist dies ein kostenpflichtiger Service, den man dann benötigt.

————————————————————
Joachim Seuling
Pionierhöhe 23
56075 Koblenz
Fax +49 (0)261-55600
Mobil +49 (0)179-5919870

**Comment by MikeMcC399** [comment]
This issue is no longer relevant and can be closed, since the TAN hotline closed down today. See [README](https://github.com/corona-warn-app/cwa-hotline/blob/master/README.md).

**Comment by dsarkar** [comment]
Dear @JoachimSeuling,

 Thanks for your proposal, please see comment https://github.com/corona-warn-app/cwa-hotline/issues/4#issuecomment-1410256950. We therefore close this issue now.

Best wishes, DS

---
Corona-Warn-App Open Source Team
