### ISSUE TITLE
Complicated URL after choosing „Personal question about Corona“

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-hotline#9]
## Which hotline
+49 800 7540001

## Current Implementation
After choosing your language and then choosing "Personal question about Corona", the voice will give you an URL. This URL contains https://. This isn't necessary.

## Suggested Enhancement 
Say 
"[infektionsschutz.de](https://www.infektionsschutz.de/)" 
instead of 
"h t t p s : / / w w w . i n f e k t i o n s s c h u t z . d e". (have to write it like that so that GitHub doesn't transform it to the link above)

## Expected Benefits
More users understanding and correctly entering the URL.

---
Internal Tracking ID:  [EXPOSUREAPP-5148](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5148)

**Comment by dsarkar** [comment]
@Ein-Tim Same here, is this still a valid issue? Thanks!

**Comment by Ein-Tim** [comment]
@dsarkar 

Yes, just checked.

**Comment by dsarkar** [comment]
@Ein-Tim ok, thanks. Internal Tracking ID:  [EXPOSUREAPP-5148](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5148)

**Comment by Ein-Tim** [comment]
This issue is still valid, over one year after I reported it.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

This issue is no longer relevant and can be closed, since the TAN hotline closed down today. See [README](https://github.com/corona-warn-app/cwa-hotline/blob/master/README.md).

**Comment by Ein-Tim** [comment]
I re-checked and this issue is still valid...

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't think any new recordings for the CWA hotline will be done anymore. I'm therefore closing this issue now.
